### PR TITLE
Add social links to plugin options page

### PR DESCRIPTION
**Pull request by renzms**
See websharks/comment-mail#286

### CODE REVIEW

**Comment by renzms** [comment]
@raamdev 

Ready for review, confirmed links open in new tab and go to respective Social Media pages.

**PRO:**

screen shot 2016-06-23 at 11 43 43 am


**LITE:**
screen shot 2016-06-23 at 11 43 03 am

**Comment by raamdev** [comment]
@renzms Can we try the social media links on a separate line? It looks a bit odd visually to have two long lines of links on either side of the page (the nav menu + the social / newsletter links).

**Comment by renzms** [comment]
@raamdev Ready for review, thanks!

**LITE**

screen shot 2016-06-29 at 12 10 43 am


**PRO**


screen shot 2016-06-29 at 12 10 04 am

**Comment by raamdev** [comment]
@renzms Would you mind committing this work to the https://github.com/websharks/comment-mail-pro/pull/76 PR? It seems that this issue and https://github.com/websharks/comment-mail-pro/pull/76 are very closely related, so merging both into the dev branch is likely to cause a merge conflict. It would be easier to just move this work into https://github.com/websharks/comment-mail-pro/pull/76.

**Comment by renzms** [comment]
@raamdev 

Hi Raam, moved the work to #76. You can close this branch. Thanks.

**Comment by raamdev** [comment]
Thanks!

**Pull request closed without merging**
