### PR TITLE
Add checkbox on templates; See: websharks/comment-mail#114

### PR DESCRIPTION
**Pull request by kristineds**
Add checkbox on templates;

- STEP 8: Add checkbox input field on Simple (shortcode-based) template
- STEP 9: Add checkbox input field on Advanced (pure PHP) template

See: websharks/comment-mail#114

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc Submitting Pull Request for Step 8/9 https://github.com/websharks/comment-mail/issues/114

**Comment by jaswsinc** [comment]
@kristineds After [this line](https://github.com/websharks/comment-mail-pro/blob/351a709ac7ad78c14ed35e73b140bf613aedf622/comment-mail-pro/includes/templates/type-s/site/comment-form/sub-ops.php#L118) add a new replacement code for the new variable that you added. e.g., `'[sub_list]' => $sub_list,`

Then edit the snippet file itself, which is what a site owner will be editing whenever they use the Simple template mode. See: https://github.com/websharks/comment-mail-pro/blob/000000-dev/comment-mail-pro/includes/templates/type-s/site/comment-form/snippet/sub-ops.php#L7

Add `[sub_list]` there.

**Comment by jaswsinc** [comment]
You might consider renaming `sub_list_options` to `sub_list_checkbox` for clarity.

**Comment by kristineds** [comment]
@jaswsinc Submitting Pull Request to add new variable for `sub_list_checkbox`. https://github.com/websharks/comment-mail-pro/commit/5ab22b5a9853c9e305a166ad2cc69965f6e32733

**Pull request merged**
