### PR TITLE
Updating path direction symbol

### PR DESCRIPTION
**Pull request by renzms**
see: websharks/comment-mail#273

### CODE REVIEW

**Comment by renzms** [comment]
screen shot 2016-06-04 at 11 54 20 pm

Replaced HTML code for `pmpPath`

**Comment by raamdev** [comment]
@renzms Did you search the entire codebase? You missed a bunch of them.

**Comment by renzms** [comment]
@raamdev 

I see what you mean. I was only searching the codebase for `pmpPath`. When I searched for the actual HTML code `&#10609`, I see there are some in `src/includes/classes/Plugin.php`

**Comment by raamdev** [comment]
@renzms Merged! Thank you. :-)

**Pull request closed without merging**
