### PR TITLE
Remove unnecessary padding in Pro Update Dashboard notification; See: websharks/comment-mail#296

### PR DESCRIPTION
**Pull request by kristineds**
Remove unnecessary padding in Pro Update Dashboard notification; 

screen shot 2016-08-26 at 2 28 46 pm

See: websharks/comment-mail#296

### CODE REVIEW

**Comment by kristineds** [comment]
@raamdev @jaswsinc This is ready for review. 😄

**Comment by raamdev** [comment]
@kristineds Have you tested this change with the other Dashboard notifications that Comment Mail produces, e.g., the StCR-related notifications that are multi-line and a bit more complex than the upgrade notice (which is only one line)?

**Comment by kristineds** [comment]
@raamdev Fixed the padding for the StCR-related notifications. https://github.com/websharks/comment-mail-pro/pull/84/commits/2ce6eacaac1d3988cbfd1d72fb154d9c4de084cc

screen shot 2016-08-30 at 11 37 28 pm

**Comment by kristineds** [comment]
@raamdev Had some problems with the Travis build last time. I've pushed this Pull Request again and all checks have passed. :) https://github.com/websharks/comment-mail-pro/pull/84/commits/e5707e3cd7f8debd0d21e443730a5280e173edf1

**Pull request closed without merging**
