### PR TITLE
Improve Dashboard notice; See: websharks/comment-mail#163

### PR DESCRIPTION
**Pull request by kristineds**
Improve Dashboard notice; 

- Improve "Upgrading from StCR" message:
- Add "Comment Mail is disabled" message

Improve CM Dashboard notice

See: websharks/comment-mail#163

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting PR for improving dashboard notice. However, I don't know how to add the link for the "Comment Mail settings" without encountering an error ~ I've tried using `%2$s`. Any help would be appreciated. Thanks! https://github.com/websharks/comment-mail-pro/commit/474948d7cd5baa3166e76e0c30e0b5321058bec0

**Comment by jaswsinc** [comment]
@kristineds You can generate the URL like this:

```php
$this->utils_urls->main_menu_page_only()
```

Referencing: https://github.com/websharks/comment-mail-pro/blob/000000-dev/comment-mail-pro/includes/classes/utils-url.php#L376

So after `esc_html($this->name)`, you should have...

```
esc_html($this->name), esc_attr($this->utils_urls->main_menu_page_only())
```

**Comment by kristineds** [comment]
@jaswsinc I'm getting this error message on my test site after adding `esc_attr($this->utils_urls->main_menu_page_only())`.

```php
Fatal error: Uncaught exception 'Exception' with message 'Undefined overload property: `utils_urls`.' in /home4/wsksdev/public_html/kristine/wp-content/plugins/comment-mail-pro/includes/classes/abs-base.php:110 Stack trace: #0 /home4/wsksdev/public_html/kristine/wp-content/plugins/comment-mail-pro/plugin.inc.php(788): comment_mail\abs_base->__get('utils_urls') #1 /home4/wsksdev/public_html/kristine/wp-content/plugins/comment-mail-pro/plugin.inc.php(2021): comment_mail\plugin->__get('utils_urls') #2 [internal function]: comment_mail\plugin->all_admin_notices('') #3 /home4/wsksdev/public_html/kristine/wp-includes/plugin.php(525): call_user_func_array(Array, Array) #4 /home4/wsksdev/public_html/kristine/wp-admin/admin-header.php(258): do_action('all_admin_notic...') #5 /home4/wsksdev/public_html/kristine/wp-admin/plugins.php(438): require_once('/home4/wsksdev/...') #6 {main} thrown in /home4/wsksdev/public_html/kristine/wp-content/plugins/comment-mail-pro/includes/classes/abs-base.php on line 110
```

**Comment by raamdev** [comment]
@kristineds Try searching the codebase for the `utils_urls()` method; maybe it doesn't exist, is called something else, or exists in a different context?

**Comment by kristineds** [comment]
@jaswsinc @raamdev Found what is causing the error! It should be `utils_url()` without the `s`. :laughing: 
https://github.com/websharks/comment-mail-pro/commit/daac098d3269860e2e5926d79f3b3de7af7cba6c

**Comment by jaswsinc** [comment]
@kristineds Cool. I knew that. I was just testing you. LMAO. ~ Sorry.

**Comment by raamdev** [comment]
@kristineds Merged. Thank you!

**Pull request closed without merging**
