### PR TITLE
Removing autocomplete for fields; 

### PR DESCRIPTION
**Pull request by renzms**
see: websharks/comment-mail#274

### CODE REVIEW

**Comment by renzms** [comment]
screen shot 2016-06-07 at 11 02 56 pm

Tested for autocomplete in Chrome.

**Comment by raamdev** [comment]
@renzms Did you test this? It's not working for me (Chrome autofill is still occurring; see yellow fields) and I see that the `autocomplete="new-password"` is not being added to the input field:

**Comment by renzms** [comment]
I tested but it wasn't filling the forms up for me, possible that I had auto-fill disabled on my browser at the time. The first time I edited a line here: src/includes/classes/MenuPage.php to add in `autocomplete="new-password"`

I think that was the mistake when it should be added here: `/src/includes/classes/FormFields.php`
screen shot 2016-06-08 at 12 45 21 am

**Comment by raamdev** [comment]
> I think that was the mistake when it should be added here: /src/includes/classes/FormFields.php

Actually, [the `inputRow()`](https://github.com/websharks/comment-mail-pro/blob/314ded19c0490883fb92ddad1d54c07b213817fa/src/includes/classes/FormFields.php#L64-L73) function is a utility function that is used for a lot of different input fields throughout Comment Mail, so we don't want the `autocomplete="new-password"` to be added to _every single input field_. We only want it to be added to the Pro Updater fields.

If you review the `inputRow()` function, you'll see it as an `other_attrs` array key that allows you to pass in extra attributes that aren't part of the default set. You can use that to call `inputRow()` with the extra `autocomplete="new-password"` attribute, that way you don't have to modify the `inputRow()` function at all.

**Pull request closed without merging**
