### PR TITLE
Add shortcodes for email footer tag; See: websharks/comment-mail#246

### PR DESCRIPTION
**Pull request by kristineds**
Add shortcodes for email footer tag; 

- Update MenuPage and add the list of shortcodes available on the **shortcodes explained** link 
- Update email footer tag snippet and added shortcodes:
   - `[home_url]`  Site home page URL; i.e., back to main site.
   - `[blog_name_clip]`  A clip of the blog's name; as configured in WordPress.
   - `[current_host_path]`  Current host/path with support for multisite network child blogs.
- Update footer email template and move email footer tag below the `<hr>` tag

screen shot 2016-03-30 at 11 44 46 pm

See: websharks/comment-mail#246

### CODE REVIEW

**Comment by kristineds** [comment]
@raamdev @jaswsinc Submitting PR. This is ready for review. :) https://github.com/websharks/comment-mail-pro/pull/62/commits/57cddfea57d6cab545a7b26ebe494347185186ba

**Comment by kristineds** [comment]
- Update advanced template to include added variables for email footer tag. https://github.com/websharks/comment-mail-pro/pull/62/commits/527e8b389a84a739d3c39b770ccfd0e7e50795ba

screen shot 2016-03-31 at 12 54 46 am

**Comment by raamdev** [comment]
@kristineds Nice work! I'll test this soon and do a thorough review this week.

**Comment by raamdev** [comment]
@jaswsinc I'd appreciate a second review from you here too, please.

**Comment by jaswsinc** [comment]
Outstanding work! Looks good to me.

**Comment by raamdev** [comment]
Reviewed and merged. Awesome work, @kristineds! :smile:

**Pull request closed without merging**
