### PR TITLE
UI Enhancement; updating plugin title. See: websharks/comment-mail#131

### PR DESCRIPTION
**Pull request by kristineds**
Closes websharks/comment-mail#131

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc Submitting PR for Comment Mail Pro websharks/comment-mail#131

**Comment by raamdev** [comment]
Reviewed. Looks good to me!

**Comment by kristineds** [comment]
@jaswsinc Added! :)

**Comment by jaswsinc** [comment]
Merged. Great! The superscript was idea was fantastic.
~ Thanks @raamdev too for testing.

**Pull request merged**
