### PR TITLE
Add syntax highlighting theme options; See: websharks/comment-mail#147

### PR DESCRIPTION
**Pull request by kristineds**
Add syntax highlighting theme options; 
-  Creating new config. option under: ​**Dashboard → Comment Mail → Config. Options → Template-Related Settings**
- Default syntax theme is `monokai`

See: websharks/comment-mail#147

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting Pull Request for Comment Mail Pro to add syntax theme dropdown options under Template-Related Settings

**Comment by jaswsinc** [comment]
@kristineds I wasn't able to test this branch due to a parse error. It looks there is an extra bracket that needs to get fixed so that we can all test your changes here.



Raam ran into this same issue when he was working on a PR earlier. He made a change in another branch so that we could test properly. If you can do the same in your PR I will come back and take another look at this.  See: https://github.com/websharks/comment-mail-pro/commit/f4b1b42eb9e0536cd4f74b1df18507f9aee83162

**Comment by raamdev** [comment]
@kristineds You should just be able to run `git pull origin && git merge 000000-dev` to merge the changes from the `000000-dev` branch into the branch you're currently working on. https://github.com/websharks/comment-mail-pro/commit/f4b1b42eb9e0536cd4f74b1df18507f9aee83162 has already been merged into `000000-dev` so there's no need to creating yet-another-commit to fix the issue.

**Comment by kristineds** [comment]
@jaswsinc @raamdev Updated changes and merged to `000000-dev` branch. :)

**Comment by raamdev** [comment]
> Updated changes and merged to 000000-dev branch. See: 68ba146 :)

You misunderstood what I said. :-) We should never be merging directly into `000000-dev`. Doing so avoids the important review process that we use the Pull Requests for. (Only after the commits in the PR are reviewed and it's decided that the PR is ready to merge, should the maintainer merge the PR into `000000-dev`). 

@jaswsinc Said that the issue I fixed in https://github.com/websharks/comment-mail-pro/commit/f4b1b42eb9e0536cd4f74b1df18507f9aee83162 was affecting your branch. Instead of repeating the same fix in your branch and creating another commit, I was simply suggesting that you merge the most recent changes **from** `000000-dev` (which includes my https://github.com/websharks/comment-mail-pro/commit/f4b1b42eb9e0536cd4f74b1df18507f9aee83162 fix) **into** the branch that you're working on. That way Jason can test your branch without being affected by that bug that I fixed. Does that make sense?

**Comment by jaswsinc** [comment]
@kristineds Thank you! :-)

I just reviewed the changes to see if they work as expected, but I'm finding that the new default theme (`monokai`) is not being applied. Actually, the only theme setting that works is `ambiance`. Here's what I'm seeing whenever I test your feature branch. Notice the template file is just a white background with black text; i.e., no CodeMirror theme.



Here is what the default configuration looks like:



---

## Next Actions

It looks like I left out an important step in order for this to work as expected. Notice [this line](https://github.com/websharks/comment-mail-pro/blob/000000-dev/comment-mail-pro/client-s/js/menu-pages.js#L35) in the JavaScript where the theme slug is hard-coded. We need to change this.

- Use the same feature branch and just push some additional tweaks.

- After [this line](https://github.com/websharks/comment-mail-pro/blob/feature/147/comment-mail-pro/plugin.inc.php#L1146) add the following:

  ```php
  'templateSyntaxTheme' => $this->options['template_syntax_theme'],
  ```

- Replace [this line](https://github.com/websharks/comment-mail-pro/blob/feature/147/comment-mail-pro/client-s/js/menu-pages.js#L35) when the following:

  ```js
  theme : vars.templateSyntaxTheme,
  ```

---

Please repeat the above steps in the [lite version](https://github.com/websharks/comment-mail/pull/154) also.

**Comment by kristineds** [comment]
@raamdev Sorry for that. Thanks for explaining it. I understood it now. :) 

@jaswsinc Submitting PR (https://github.com/websharks/comment-mail-pro/commit/df9aaf5fcbc10bb60d67fe802208bce1ec38ecb0) with for this JS tweak.

**Comment by raamdev** [comment]
@jaswsinc I reviewed this and it looks good to me.

**Comment by jaswsinc** [comment]
@kristineds Looks great! One minor enhancement please.

Please replace [this line](https://github.com/websharks/comment-mail-pro/blob/feature/147/comment-mail-pro/includes/classes/menu-page.php#L1736) with the following note to help others understand what this setting does.

```php
'notes_after' => '<p>'.__('This changes the syntax highlighting color scheme used in textarea fields; e.g., Email Templates and Site Templates.', $this->plugin->text_domain).'</p>',
```

**Comment by kristineds** [comment]
@jaswsinc Code for that enhancement has been added. :) https://github.com/websharks/comment-mail-pro/commit/5e400c61cf5ef57aa74030ee492efd70d06bda2f

**Comment by jaswsinc** [comment]
Merged. Thanks @kristineds :100:

**Pull request merged**
