### PR TITLE
PR: feature/114

### PR DESCRIPTION
**Pull request by jaswsinc**
See: websharks/comment-mail#114

### CODE REVIEW

**Comment by raamdev** [comment]
> When a user confirms their comment subscription it will also automatically confirm their mailing list subscription at the same time.

What if comment subscription confirmations are disabled? Does the normal MailChimp subscription confirmation email go out?

**Comment by raamdev** [comment]
FYI, I updated first comment to indicate correct GitHub issue (should be websharks/comment-mail#114 not websharks/comment-mail-pro#114).

**Comment by jaswsinc** [comment]
> What if comment subscription confirmations are disabled? Does the normal MailChimp subscription confirmation email go out?

I'm adjusting the system to account for that scenario as well, as described in the screenshot below.

**Comment by jaswsinc** [comment]
Adding additional config options for MailChimp.

**Comment by jaswsinc** [comment]
@raamdev This is ready to merge. Please review when you have a moment.

I performed several tests, but here is a list of tests that I feel would be helpful; i.e., scenarios I have not yet tested myself. My feeling is these will test positive and without issue, but worth running through if Renz has time.
### Tests Remaining

- [ ] Test MailChimp integration with Advanced templates instead of Simple templates.
- [ ] Test with auto-confirm enabled; i.e., where users are not required to confirm.

**Comment by jaswsinc** [comment]
Merging this myself but feel free to review.

**Comment by renzms** [comment]
@jaswsinc / @raamdev 

> Tests Remaining
> 
> - [ ] Test MailChimp integration with Advanced templates instead of Simple templates.

Tested with Advanced templates, didn't notice anything wrong, was there any specific case you wanted me to test for failure?

>- [ ] Test with auto-confirm enabled; i.e., where users are not required to confirm.

_(edited the email address, but I received the auto-confirmation email when enabling Auto-Confirm)_

**Confirmed working** 👍 
screen shot 2016-11-04 at 9 24 23 pm


_____

However noticed a fatal error when unsubscribing, trying to comment again while **Auto-Confirm** is `enabled`.

## Observed Behaviour:  Fatal Error

```
Fatal error: Uncaught Mailchimp_List_InvalidUnsubMember: tester@gmail.com has unsubscribed, and cannot be resubscribed by you. To prevent false spam complaints, they'll need to resubscribe of their own free will. in /app/src/wp-content/plugins/comment-mail-pro/src/vendor/mailchimp/mailchimp/src/Mailchimp.php on line 253 Mailchimp_List_InvalidUnsubMember: tester@gmail.com has unsubscribed, and cannot be resubscribed by you. To prevent false spam complaints, they'll need to resubscribe of their own free will. in /app/src/wp-content/plugins/comment-mail-pro/src/vendor/mailchimp/mailchimp/src/Mailchimp.php on line 253 Call Stack: 0.0004 396320 1. {main}() /app/src/wp-comments-post.php:0 0.0391 3508904 2. wp_handle_comment_submission() /app/src/wp-comments-post.php:20 0.0413 3547136 3. wp_new_comment() /app/src/wp-includes/comment.php:2923 0.0717 3558016 4. do_action() /app/src/wp-includes/comment.php:1824 0.1220 4346952 5. WebSharks\CommentMail\Pro\Plugin->commentPost() /app/src/wp-includes/plugin.php:524 0.1258 4365448 6. WebSharks\CommentMail\Pro\CommentPost->__construct() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/Plugin.php:2578 0.1285 4498600 7. WebSharks\CommentMail\Pro\CommentPost->maybeInjectSub() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/CommentPost.php:54 0.1344 4800432 8. WebSharks\CommentMail\Pro\SubInjector->__construct() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/CommentPost.php:95 0.1385 5102992 9. WebSharks\CommentMail\Pro\SubInjector->maybeInject() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/SubInjector.php:142 0.1446 5452352 10. WebSharks\CommentMail\Pro\SubInserter->__construct() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/SubInjector.php:199 0.1453 5469792 11. WebSharks\CommentMail\Pro\SubInserter->maybeInsertUpdate() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/SubInserter.php:479 0.1503 5625344 12. WebSharks\CommentMail\Pro\SubInserter->insert() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/SubInserter.php:695 0.1900 5792512 13. WebSharks\CommentMail\Pro\UtilsListServer->maybeSubscribe() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/SubInserter.php:772 0.1907 5814288 14. WebSharks\CommentMail\Pro\ListServerMailchimp->subscribe() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/UtilsListServer.php:37 0.1989 6530480 15. call_user_func_array:{/app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/ListServerMailchimp.php:66}() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/ListServerMailchimp.php:66 0.1990 6530984 16. Mailchimp_Lists->subscribe() /app/src/wp-content/plugins/comment-mail-pro/src/includes/classes/ListServerMailchimp.php:66 0.1990 6531400 17. Mailchimp->call() /app/src/wp-content/plugins/comment-mail-pro/src/vendor/mailchimp/mailchimp/src/Mailchimp/Lists.php:744
```

## Steps to Reproduce

- Enable **Auto-Confirm** in dropdown , `Yes, automatically auto-confirm everyone; i.e., never ask for email confirmation`
- Test and comment to auto-subscribe and receive the auto-confirmation email.
- Click `unsubscribe` from the auto-confirmation email
- Test and comment again with **Auto-Confirm** still enabled
- See Error prompt above

**Comment by raamdev** [comment]
@renzms This PR has been is merged and is closed now. Can you copy the above comment to https://github.com/websharks/comment-mail/issues/114 and update the comment above to point to the new comment on https://github.com/websharks/comment-mail/issues/114?

**Pull request merged**
