### PR TITLE
Remove IP address in notification emails; See:websharks/comment-mail#288

### PR DESCRIPTION
**Pull request by kristineds**
Remove IP address in notification emails; 

Subscriber IP address removed in these templates:

- `/src/includes/templates/type-a/email/sub-confirmation/message.php`
- `/src/includes/templates/type-s/email/sub-confirmation/message.php`

Configurable in  **Email Subscr. Confirmation Message Body Template** in Comment Mail Dashboard

screen shot 2016-07-27 at 1 28 17 pm

screen shot 2016-07-27 at 1 21 39 pm

See:websharks/comment-mail#288

### CODE REVIEW

**Comment by kristineds** [comment]
@raamdev @jaswsinc This is ready for review. https://github.com/websharks/comment-mail-pro/pull/79/commits/d6b6063e10fdb3f240634748ba9c9955c0c9b70d

**Comment by raamdev** [comment]
@kristineds It looks like you removed the entire line, when we really just want to remove the IP address portion, not the entire line.

**Comment by kristineds** [comment]
@raamdev Thanks for the feedback. I have added the line back and removed only the IP address section. https://github.com/websharks/comment-mail-pro/pull/79/commits/9d52be16510164cbfe5b72b06a2936708d45d64f 

screen shot 2016-07-30 at 8 52 46 am

**Comment by raamdev** [comment]
@kristineds It looks like you removed the date from that line as well. The date can stay in.

**Comment by kristineds** [comment]
@raamdev I've added the date back in. :) See: https://github.com/websharks/comment-mail-pro/pull/79/commits/27173da97f11878907509d74e55809fcd5e80669

**Comment by raamdev** [comment]
@kristineds Awesome. This looks great to me. Thank you!

**Pull request closed without merging**
