### PR TITLE
Fix Pro Preview Link and alignment of menu items;

### PR DESCRIPTION
**Pull request by renzms**
see: websharks/comment-mail#227

### CODE REVIEW

**Comment by renzms** [comment]
@raamdev / @jaswsinc 

Ready for review, please see screenshot

Tested using: (`.~build/comment-mail/.~build/comment-mail.zip` after running **phing**
screen shot 2016-03-31 at 9 32 55 pm
).

**Comment by raamdev** [comment]
_@renzms Note that I've updated this branch with the latest changes from `000000-dev`, so you'll need to `git pull` on this branch before making anymore commits._

----

There's still a problem with the horizontal rule cutting into the links. Try testing it when the "StCR Auto-Import" text appears under the "Import/Export" link (which appears when you have StCR Subscriptions in your database that have not been imported into Comment Mail):

**Comment by renzms** [comment]
@raamdev 

Hi Raam, I wasn't able to get the StCR Auto-Import to appear on the Options header. I created some new test subscriptions for StCR and did not import them into Comment Mail. Anything else specific I need to do to get the option to appear?

screen shot 2016-04-18 at 9 48 29 pm

**Comment by jaswsinc** [comment]
@renzms Try playing with the conditions in this line so the link will show during your tests. See: https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/classes/MenuPage.php#L4606

**Comment by renzms** [comment]
@jaswsinc Thanks for the tip! 

@raamdev Ready for review, please see screenshots:

Wide Desktop:
screen shot 2016-04-25 at 9 34 26 pm

Smaller Screens:
screen shot 2016-04-25 at 9 34 43 pm

**Comment by raamdev** [comment]
@renzms FYI, I merged the latest from `000000-dev` into this branch, so you'll need to `git pull`.

----

The Pro version looks fine, but the Lite version still has some issues:

**Comment by renzms** [comment]
@raamdev 

Hi Raam, ran `git pull && git submodule update.` I ran phing afterwards and got an error, so ran it a second time and it was okay. 

Anyway, do I test also for the lite version using: `.~build/comment-mail/.~build/comment-mail.zip`?

Sorry, I was under the impression that working on Comment Mail Pro would also cover for the lite version of the plugin.

**Comment by raamdev** [comment]
> Sorry, I was under the impression that working on Comment Mail Pro would also cover for the lite version of the plugin.

There's just one codebase (the Pro codebase), but the Phing build script does stuff to Pro codebase to _generate a Lite version_. So, it's always important to be testing both generated Pro version _and_ the generated Lite version.

> Anyway, do I test also for the lite version using: .~build/comment-mail/.~build/comment-mail.zip?

Yes, that's the path to the generated Lite version.

**Comment by renzms** [comment]
@raamdev @jaswsinc 

Hi Guys,

Just noticed that in `.~build/comment-mail/.~build/comment-mail.zip`, the files and folders are not updating on my local repo. After running phing, everything in the `.~build/comment-mail/.~build/` folder is still from April 25. Only the comment-mail-pro distributable is updating when I run `phing`.

Any reason why it would be doing that? I ran `git submodule init && git submodule update && git submodule sync`, and still no changes to the Comment Mail Lite distributable after running `phing`.

**Comment by raamdev** [comment]
> Just noticed that in .~build/comment-mail/.~build/comment-mail.zip, the files and folders are not updating on my local repo. After running phing, everything in the .~build/comment-mail/.~build/ folder is still from April 25. Only the comment-mail-pro distributable is updating when I run phing.

The build system changed recently. You need to run `phing build-all` to build both the Pro and Lite version in `.~build/`.

**Comment by renzms** [comment]
> The build system changed recently. You need to run phing build-all to build both the Pro and Lite version in .~build/.

@raamdev 

Thanks, taking note of that. Would I need to do that from now on everytime I run `phing`?

Updated, and tested for both Lite and Pro scenarios. I included the logo back in the Pro test and also tested without it to make sure it the horizontal bar doesn't move too far up or down.


**Lite:**
screen shot 2016-05-07 at 7 48 13 am

**Pro:**
screen shot 2016-05-07 at 8 09 57 am

**Comment by raamdev** [comment]
@renzms Just tested this again; still not looking right:



Increasing the padding on the bottom of the heading to `4em` seems to fix this:

```
.comment-mail-menu-page .pmp-heading { padding-bottom: 4em; }
```



I confirmed that fix also works for the Lite version:

**Comment by renzms** [comment]
@raamdev 

Was originally at `4em` but looked off, seems I forgot to change the status during testing of this: https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/classes/MenuPage.php#L4606 to have the **StCR Auto-Import** appear again. Changing now.

**Comment by raamdev** [comment]
@renzms Now it doesn't look right when the "Auto-Import" isn't there:



Please test all of the scenarios that we've gone through in this issue, both Pro and Lite, to confirm it looks right, including when the browser is resized, with and without Dashboard notices above it.

**Comment by renzms** [comment]
@raamdev 

Tried to be thorough as possible with all scenarios possibles. This is as balanced as I could get it without it overlapping or having too much of a huge gap.


**Pro
Normal**
**- Logo**
— Dashboard Notices
-— STCR auto import enabled
-— STCR auto import disabled
— Without Dashboard notices
-— STCR auto import enabled
-— STCR auto import disabled

pro 1
pro 2
pro 3
pro 4


**- No logo**
— Dashboard Notices
-— STCR auto import enabled
-— STCR auto import disabled
— Without Dashboard notices
-— STCR auto import enabled
-— STCR auto import disabled


pro 5
pro 6
pro 7
pro 8

**Resized
- Logo**
— Dashboard Notices
-— STCR auto import enabled
-— STCR auto import disabled
— Without Dashboard notices
-— STCR auto import enabled
-— STCR auto import disabled

pro 9
pro 10
pro 11
pro 12


**- No logo**
— Dashboard Notices
-— STCR auto import enabled
-— STCR auto import disabled
— Without Dashboard notices
-— STCR auto import enabled
-— STCR auto import disabled

pro 13
pro 14
pro 15
pro 16

______

**Lite
Normal**
 **- No logo**
— Dashboard Notices
-— STCR auto import enabled
-— STCR auto import disabled
— Without Dashboard notices
-— STCR auto import enabled
-— STCR auto import disabled

lite 1
lite 2
lite 3
lite 4



**Resized
- No logo**
— Dashboard Notices
-— STCR auto import enabled
-— STCR auto import disabled
— Without Dashboard notices
-— STCR auto import enabled
-— STCR auto import disabled
lite 5
lite 6
lite 7
lite 8

**Comment by raamdev** [comment]
@renzms Nice! I love all of those screenshots! 👍 👍  

I'd say that's consistent enough for now. We really need to rework the entire menu page UI to make it work better on mobile devices, so I'd say we can call this done and leave any other work on this specific issue to when we work on refreshing the UI.

**Comment by jaswsinc** [comment]
👏 @renzms

**Pull request closed without merging**
