### PR TITLE
Improve Pro Options Panel header when logo is hidden

### PR DESCRIPTION
**Pull request by renzms**
See websharks/comment-mail#284

### CODE REVIEW

**Comment by renzms** [comment]
@raamdev 

- Removed the `Restore` button
- Made it a link
- Tested, link prompts the dialog box asking if user is *sure they want to restore settings*


## With Logo
screen shot 2016-06-24 at 8 02 07 am




**Problem**

____
## Without Logo

Header has extra white space and margin. Editing the padding and margins move around the division bar between heading and content.
screen shot 2016-06-24 at 8 10 02 am


Adjusted the CSS to make it so that the body's positioning would determine the position of the bar, since the header is variable (logo optional, different pro/lite header links, etc), but the body would always have a fixed position.

For some reason though, the division bar ends at the bottom of the panel, although the CSS is using `::before`

screen shot 2016-06-24 at 9 05 48 am

**Comment by jaswsinc** [comment]
@renzms I updated this PR with [some tweaks](https://github.com/websharks/comment-mail-pro/pull/76/commits/96ad8fbd851b84baa0392d523d62d763d8b7dc74) to assist you. Please review and if you find it acceptable please notify Raam so he can do a review and merge.

## Screenshots



---



---



---

**Comment by jaswsinc** [comment]
@renzms writes...

> division bar ends at the bottom of the panel, although the CSS is using ::before


The `::before` decides where the content element will be inserted into the DOM. It doesn't decide how it is positioned inside the element is inserted into. In this case, the element is inserted into the DOM `::before` all other elements, and then positioning absolutely to the `bottom: 0`.

**Comment by renzms** [comment]
@jaswsinc Thanks for the assist! It all looks better to me! So instead of a division bar, it will have the "note" to divide the header and the content?

@raamdev What do you think?

**Comment by jaswsinc** [comment]
@renzms writes...

> have the "note" to divide the header and the content?

The notice is there, but it's not responsible for being the divider, because it may or may not apply; i.e., it may not be shown in all cases, so we can't rely upon that element. That notice just needs to fit properly whenever it is present is all.

What I did is I set a new `::after` pseudo selector to force a clearing of the heading. Then I removed the padding and adjusted the margin on the notice when it's present. See: https://github.com/websharks/comment-mail-pro/pull/76/commits/96ad8fbd851b84baa0392d523d62d763d8b7dc74#diff-6d5698e58e9090f25b226ff8f1ce1769R682

**Comment by renzms** [comment]
Work from #74 :

**LITE**

screen shot 2016-06-29 at 12 10 43 am


**PRO**


screen shot 2016-06-29 at 12 10 04 am

**Comment by renzms** [comment]
@raamdev 

Hi Raam, between the work from #75 : (Add social links to plugin options page) and @jaswsinc 's updated responsive tweaks above, is there anything else we can improve upon for this featured branch?

**Comment by raamdev** [comment]
@renzms This looks great! I just ran it through a few tests. Beautiful! I love how the whole thing adapts to the browser even when it's mobile-size.

**Comment by raamdev** [comment]
There was a small issue with the spacing between links:



Fixed in https://github.com/websharks/comment-mail-pro/pull/76/commits/85428a3fafa87a832a796b0ed9d5f816aca089a0:

**Pull request closed without merging**
