### PR TITLE
Pre-populate name/email fields on Add new subscription form; See: websharks/comment-mail#204

### PR DESCRIPTION
**Pull request by kristineds**
Pre-populate name/email fields on Add new subscription form; 

screen shot 2016-01-29 at 8 10 25 am

See: websharks/comment-mail#204

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev I'm submitting the PR for this with the code you provided but it's _not_ pre-populating the fields for the last name and email fields?

**Comment by jaswsinc** [comment]
@kristineds Were you logged into the site whenever you tested this?

**Comment by kristineds** [comment]
> Were you logged into the site whenever you tested this?

@jaswsinc When I was logged-in as a user, only the "First name" is pre-populated. 

This works perfectly, i.e. email and first name fields are pre-populated, when a cookie exists from previously leaving a comment.

**Comment by jaswsinc** [comment]
> When I was logged-in as a user, only the "First name" is pre-populated

And I assume that your account in WordPress had both the First and Last name filled? In other words, do you feel there is a bug in that specific scenario? Or was the Last name missing from the form because it was missing in your account profile in WordPress?

**Comment by jaswsinc** [comment]
> This works perfectly, i.e. email and first name fields are pre-populated, when a cookie exists from previously leaving a comment.

Cool!

**Comment by raamdev** [comment]
@kristineds Can we get an update here?

**Comment by kristineds** [comment]
@jaswsinc @raamdev I tested this again. See below for my observations. What are the possible causes for this?

- Signed up and registered for a new user account: http://kristine.websharks-inc.net/wp-login.php _(Site has no other plugins enabled except Comment Mail Pro)_
- Logged in with credentials and edited profile, added first name and last name

screen shot 2016-02-02 at 10 29 02 pm

- Went back to a post and selected "you can subscribe without commenting"

screen shot 2016-02-02 at 10 18 39 pm

- Got redirected to the Add New Subscription Form. First name is pre-populated but **not** that Email and Last name fields. 

screen shot 2016-02-02 at 10 30 12 pm

**Comment by jaswsinc** [comment]
@kristineds My [last commit/tweak](https://github.com/websharks/comment-mail-pro/commit/9e2e6d782a116b24e97b07945177125d0fbbe294) should correct this behavior. Working good on my side. If you can test it and confirm I'd appreciate it. Also, if it works for you, can you apply the same to the lite PR?

**Comment by kristineds** [comment]
@jaswsinc Got the `last name` to show up but not the `email`. That should be filled since `email` is a required field, isn't it? 

screen shot 2016-02-03 at 11 55 36 am

_I'll be submitting the one for the Lite PR, so it's easier to track the changes for both_

**Comment by jaswsinc** [comment]
@kristineds Try changing `$current->email` to `$current->user_email`.

**Comment by kristineds** [comment]
@jaswsinc That works. Thanks! :+1: This is ready for review. @raamdev

**Comment by raamdev** [comment]
@kristineds Reviewed, tested, and merged. Nice work! Thank you.

**Pull request closed without merging**
