### PR TITLE
Remove x on Status and deliver fields; See: websharks/comment-mail#195

### PR DESCRIPTION
**Pull request by kristineds**
Remove `x` on Status and deliver fields; 

See: websharks/comment-mail#195

### CODE REVIEW

**Comment by kristineds** [comment]
Please see my comment [here](https://github.com/websharks/comment-mail/issues/195#issuecomment-170754441) regarding this issue.

**Comment by kristineds** [comment]
@jaswsinc @raamdev Please see my [comment here](https://github.com/websharks/comment-mail/issues/195#issuecomment-171895134).

**Comment by jaswsinc** [comment]
I reviewed this PR and left some comments here.
https://github.com/websharks/comment-mail/issues/195#issuecomment-172426083

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting PR for Pro version to remove clear option for the Status and Deliver fields on the Edit Subscription form (front-end). https://github.com/websharks/comment-mail-pro/commit/196e05ea61bf40e4fae27f72a6ecadcb885bb842

screen shot 2016-01-27 at 4 59 10 am

**Comment by jaswsinc** [comment]
This looks great to me. Beautiful!
~ @raamdev This looks ready to merge.

**Pull request closed without merging**
