### PR TITLE
PR: feature/150

### PR DESCRIPTION
**Pull request by jaswsinc**
See: websharks/comment-mail#150

### CODE REVIEW

**Comment by jaswsinc** [comment]
## Summary of Changes

- ### [PSR 4](http://www.php-fig.org/psr/psr-4/) Compliance

  - Comment Mail is not integrated with Composer instead of using Submodules.
  - Comment Mail now uses the Composer autoloader instead of its own autoloader.
  - Comment Mail now follows namespace and class file naming standards.

  #### Local Development (attn: Kristine/Renz)

  ```bash
  $ git clone git@github.com:websharks/comment-mail-pro.git
  $ cd comment-mail-pro
  $ composer install
  ```

---

- ### PSR [1](http://www.php-fig.org/psr/psr-1/) & [2](http://www.php-fig.org/psr/psr-2/) Compliance; i.e., style guidelines, code formatting.

  The [PSR 1/2 guidelines](http://www.php-fig.org/psr/) require 4-**space** indents (not tabs) and several other coding standards. It's a good idea to read over [the guidelines](http://www.php-fig.org/psr/) carefully, as they will be required in all PRs soon; i.e., once we implement a CI tool w/ GitHub, if your PR does not adhere to these guidelines, that will cause it to fail validation and your PR will not be merged.

  #### You can automatically format your source code using one of these.

  - PHP CS Fixer (recommended), which is bundled with the [WS Atom Toolbox](https://atom.io/packages/ws-toolbox).
  - Or, by running [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) as a command-line tool. Be sure to run it with [this config file](https://github.com/websharks/dotfiles/blob/000000-dev/.php_cs).

  - Or, w/ PhpStorm; WebSharks PSR-1/2 style. Updated. See: https://cloudup.com/c2ZbZls0ZEa
  
     The [WebSharks PSR-1/2 style for PhpStorm](https://cloudup.com/c2ZbZls0ZEa) was tweaked just a teeny bit in order to bring it closer to what PHP CS Fixer does. I am sharing it via CloudUp for the moment. I'll wait for Raam's OK to update the [websharks/phpstorm](https://github.com/websharks/phpstorm) repo with the latest settings, just in case he would like to be the one to update the websharks/phpstorm repo.

  #### PHP CS Fixer vs. PhpStorm Formatting

  They are both great tools.

  PhpStorm has the absolute best code formatter I have ever seen, and I still miss it, even though I don't use PhpStorm any longer. It is quite comprehensive and easily configurable.

  PHP CS Fixer is also a code formatter, but _formatting_ (i.e., converting any mess of code into a clean and tidy work of art) is not it's primary objective. It's primary objective is to make your code PSR 1/2 compliant, and it does a decent job at this. However, it's not always perfect, and in fact it sometimes skips over things on purpose, leaving them for you to fix yourself. This is, in part, because PHP CS Fixer is really meant to be used in concert with PHP Code Sniffer as your linter. PHP CS Fixer is designed specifically to get you past lint checks performed by [PHP Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer). Two different applications. One is a lint checker, and the other is a lint cleaner (fixer).

  #### PHP Code Sniffer + PHP CS Fixer

  First, let me explain that the PHP Code Sniffer (not the fixer, the lint checker), is what I use to lint-check our code, and it is what most CIs use also. It's an open-source command-line tool that is easy to work with, easy to configure, and you can integrate it into many different applications or on a server (e.g., a CI server). Whenever we finally do introduce a CI, it's going to include PHP Code Sniffer in order to help us enforce PSR standards.

  So, with that in mind, we should all start using PHP Code Sniffer to lint-check our code while we are working on projects like Comment Mail, ZenCache, the websharks/core, websharks/wp-core, websharks/s2member-x, and others in the future. No matter which code styling/formatter you choose to work with; after you format your code, you should run your code through PHP Code Sniffer to be sure it's going to pass validation. WebSharks follows the PSR 1/2 standards, with just a few very minor exceptions, which makes our standards slightly more lenient.

  Here is the config file that I'm planning to use for the CI server that will validate our code.
  https://github.com/websharks/dotfiles/blob/000000-dev/.php-cs.ws-psr2.xml
  _You can use this same config file on your own system. It comes with the WS Atom Toolbox also._

  Now, the reason I use PHP CS Fixer instead of PhpStorm, is because PHP CS Fixer is designed specifically to fix your code and make it pass PHP Code Sniffer tests. It's better at _fixing_ PSR-specific issues, but not as good at _formatting_ a mess. PhpStorm is still king at this.

  For me though, PHP CS Fixer the _The Right Tool for the Job™_ when it comes to maintaining standards, and I find it's the only tool I need when it comes to formatting. However, it really doesn't matter. Take your pick. PhpStorm or PHP CS Fixer. So long as your code passes PHP Code Sniffer lint checks.

  If you decide to use PHP CS Fixer instead of PhpStorm, I recommend using it together with a great linter; e.g., Atom has a fantastic lint-checking interface and I use that together with PHP CS Fixer.

  - https://atom.io/packages/linter
  - https://atom.io/packages/linter-phpcs
  - https://atom.io/packages/ws-toolbox

---

- ### Phing Build Routine

  - Comment Mail is now built with a PSR-4 Phing script developed by Raam/Jason.

---

- ### One Codebase (Automatic Lite Generation; Partial Completion)

  - Comment Mail is now a single codebase capable of building the Lite version automatically.

  - [ ] However, we need to fork another issue, so we can spend time adding more `/*[pro strip-from="lite"]*/ /*[/pro]*/` markers to the codebase. I added some of the most important ones to start with; e.g., no pro updater, no pings back to our stats server, no pro options allowed, and the menu page adjusts automatically with a pro preview in the lite version. However, the rest of the lite version is still filled with a lot of pro-only features. So there is still some work to be done on this. We just need to add a few more of the `/*[pro strip-from="lite"]*/ /*[/pro]*/` markers in various places.

---

- ### Bugs Fixed

  - https://github.com/websharks/comment-mail/issues/173
  - https://github.com/websharks/comment-mail/issues/230

---

- ### New Namespace Constants like Comet Cache

  ```php
  define(__NAMESPACE__.'\\QV_PREFIX', 'cm_');
  define(__NAMESPACE__.'\\SHORT_NAME', 'CM');
  define(__NAMESPACE__.'\\NAME', 'Comment Mail');
  define(__NAMESPACE__.'\\DOMAIN', 'comment-mail.com');
  define(__NAMESPACE__.'\\GLOBAL_NS', 'comment_mail');
  define(__NAMESPACE__.'\\SLUG_TD', 'comment-mail');
  define(__NAMESPACE__.'\\TRANSIENT_PREFIX', 'cmtmail_');
  define(__NAMESPACE__.'\\VERSION', ${__FILE__}['version']);
  define(__NAMESPACE__.'\\PLUGIN_FILE', ${__FILE__}['plugin']);
  define(__NAMESPACE__.'\\IS_PRO', ${__FILE__}['is_pro']);
  ```

  Comment Mail has two that Comet Cache does not have yet.

  - `QV_PREFIX`
  - `TRANSIENT_PREFIX`

**Comment by jaswsinc** [comment]
See also, the important note I left here:
https://github.com/websharks/comment-mail/issues/150#issuecomment-184048340

> Noting that existing custom templates out-in-the-wild will be broken by these changes. Simple templates will remain functional, but Advanced PHP templates that have been customized in previous versions will no longer work after these changes.

**Comment by raamdev** [comment]
Noting what I had to do after checking out and `git pull`ing this `feature/150` branch:

```shell
$ rm -rf comment-mail-pro/ # this contained submodules that couldn't be automatically removed during `git pull`
$ git submodule init && git submodule update # to get the phings submodule 
```

**Comment by jaswsinc** [comment]
_Unrelated to the previous comment. I'm just referencing:_
https://github.com/websharks/comment-mail/issues/237

**Comment by jaswsinc** [comment]
@raamdev I just pushed two more commits to this branch in order to resolve a minor issue with caSe in file names. I noticed that Git didn't pick up some of the `StudlyCap` class file name changes. So I pushed two commits to force that to update on the GitHub side.

**Comment by raamdev** [comment]
@jaswsinc Reviewed, tested, and merged. Super awesome! :tada: :+1: :100: Thank you! :smile:

**Pull request closed without merging**
