### PR TITLE
Simplify config sub-section menu items; See: websharks/comment-mail#187

### PR DESCRIPTION
**Pull request by kristineds**
Simplify config sub-section menu items; 

- Rename "Restore Default Options" to "Restore", move designated icon to end of the text, and convert text link to blue button (green on hover)
- Add "Beta Testers" text link with icon
- Move "Restore" button, "Newsletter","Beta Testers" text link to upper right side of plugin options panel

![Simplify sub section menu items - v1.0]
(https://cloud.githubusercontent.com/assets/7514953/12353155/28be6332-bbc7-11e5-8152-655e2c539f7a.png)

See: websharks/comment-mail#187

### CODE REVIEW

**Comment by kristineds** [comment]
_NOTE: This is a work-in-progress. Still working on the following:_

- Display installed version number on plugin options panel
- Display Pro Updater link right next to the Newsletter link

**Comment by jaswsinc** [comment]
I reviewed the work thus far, and left some comments here.
https://github.com/websharks/comment-mail/issues/187#issuecomment-172421928

**Comment by raamdev** [comment]
@kristineds Is this ready for review or are you still working on this?

**Comment by kristineds** [comment]
> Is this ready for review or are you still working on this?

I can submit the PR for the displaying the version number but I'm trying to figure out how to display the Pro Updater ~ I would need your help on this.

**Comment by kristineds** [comment]
@raamdev Here is the PR for displaying the version number. https://github.com/websharks/comment-mail-pro/commit/1e52ea982cab23b230ceeb6b32379b1f7cdf49e1

screen shot 2016-01-27 at 2 18 59 am

**Comment by raamdev** [comment]
@kristineds writes...
> how to display the Pro Updater

Do you mean checking if there's a newer version and then linking to the Pro Updater when an update is available?

**Comment by kristineds** [comment]
@raamdev writes..

> Do you mean checking if there's a newer version and then linking to the Pro Updater when an update is available?

Yes. I posted my attempted code [here](https://github.com/websharks/comment-mail/issues/187#issuecomment-171976382) but it only checks if the plugin is using the Pro version but it doesn't check if it is using a newer version.

**Comment by raamdev** [comment]
@kristineds Can I get an update here? Is this PR ready for review? I don't see any updates after your last comment, however I see that Jason did leave a few replies here: https://github.com/websharks/comment-mail/issues/187#issuecomment-172421928

**Comment by kristineds** [comment]
@raamdev @jaswsinc This is ready for review.

screen shot 2016-02-04 at 2 16 37 pm

Changelog:

- Rename "Restore Default Options" to "Restore", move designated icon to end of the text, and convert text link to blue button (green on hover)
- Add "Beta Testers" [text link](http://www.comment-mail.com/beta%20testers) with icon
- Move "Restore" button, "Newsletter","Beta Testers" text link to upper right side of plugin options panel
- Show installed version number (https://github.com/websharks/comment-mail-pro/commit/64bd885dc7373dfd3514cd638437c93f07dfdc66)
- Show Pro Updater link right next to the Newsletter link (https://github.com/websharks/comment-mail-pro/commit/3266e9c3b24116c1a98ef3d56edf680c74883476)

**Comment by raamdev** [comment]
@kristineds As explained in https://github.com/websharks/comment-mail/pull/212#issuecomment-180659932, please adjust the formatting a bit so that everything lines up on the right edge:

**Comment by kristineds** [comment]
@raamdev Is this supposed to be assigned to @renzms? Or was that a mistake? :) 
I'm reassigning this to myself since I already started working on it. Here's the PR for the Pro version with the alignment adjusted: https://github.com/websharks/comment-mail-pro/commit/90ca51fd6ed96594baf58f5b2c6dc5300851a6e5

screen shot 2016-02-07 at 12 38 22 am

**Comment by raamdev** [comment]
> Is this supposed to be assigned to @renzms? Or was that a mistake? :)

That was a mistake, sorry. :-)

The screenshot looks great, however I noticed that GitHub is reporting there are conflicts that must be resolved. Have you been merging `000000-dev` into your feature branch(es) regularly?

**Comment by kristineds** [comment]
> however I noticed that GitHub is reporting there are conflicts that must be resolved. Have you been merging 000000-dev into your feature branch(es) regularly?

That's odd. Yes, I have been doing that. I followed @jaswsinc suggestion on using an alias for it.

```
$ git config --global alias.fmdev '!git fetch --all && git merge 000000-dev'
```

Should I redo it?

**Comment by raamdev** [comment]
@kristineds Can you try resolving the merge conflicts on your end? 

- https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#Basic-Merge-Conflicts
- https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging#Merge-Conflicts
- http://weblog.masukomi.org/2008/07/12/handling-and-avoiding-conflicts-in-git/

**Comment by kristineds** [comment]
@raamdev I'm getting this:

```bash
Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   comment-mail-pro/includes/classes/menu-page.php
```

How do I fix it? I used `git mergetool` but I got this:

```bash
This message is displayed because 'merge.tool' is not configured.
See 'git mergetool --tool-help' or 'git help config' for more details.
'git mergetool' will now attempt to use one of the following tools:
opendiff kdiff3 tkdiff xxdiff meld tortoisemerge gvimdiff diffuse diffmerge ecmerge p4merge araxis bc codecompare emerge vimdiff
Merging:
comment-mail-pro/includes/classes/menu-page.php

Normal merge conflict for 'comment-mail-pro/includes/classes/menu-page.php':
  {local}: modified file
  {remote}: modified file
Hit return to start merge resolution tool (opendiff):
xcode-select: error: tool 'opendiff' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
comment-mail-pro/includes/classes/menu-page.php seems unchanged.
```

**Comment by raamdev** [comment]
@kristineds You need to review the `comment-mail-pro/includes/classes/menu-page.php` manually and see where the conflicts appear, then choose between the two conflicting pieces of code. You'll need to delete the conflicting code and fix up the file so that it looks right.

**Comment by kristineds** [comment]
@raamdev I was able to resolve the conflict by pushing it as a commit. However, in doing so, it pushed the other commits from the other feature branches ~ after I used `git pull` for `feature/187` . :disappointed:  How do I fix or undo this commit? Thank you! cc @jaswsinc

**Comment by raamdev** [comment]
@kristineds No problem. This PR looks fine now (i.e., there are no merge conflicts). When you merge `000000-dev` into your feature branch (so that all of the other commits that were merged into `000000-dev` get added to your feature branch), you normally commit that merge as a single commit, e.g., "Merging 000000-dev into feature/187". 

It looks like what happened here is you did the merge _and_ committed some work in the same commit (https://github.com/websharks/comment-mail-pro/commit/11f0bc8059631eb407fbc19d9c5cb1ef81ef8bf8).

Not a big deal. It just makes it harder to see what you actually changed in https://github.com/websharks/comment-mail-pro/commit/11f0bc8059631eb407fbc19d9c5cb1ef81ef8bf8 that _wasn't_ part of the merge, and your commit message doesn't indicate that the commit was actually a merge. Really not a big deal. The code was properly merged and conflicts were resolved, and that's what matters. 

---

In the future, remember that anything you **push** to GitHub cannot be easily be "undone". If you're pushing to a feature branch, it's no big deal because worst case scenario you can just delete the feature branch and start over. However, you should generally try to get things fixed on your local computer _before_ you push. For example, if you commit something locally, you can undo that commit and try again. Once you push to GitHub, the only way to undo a commit is to push another commit that reverts the previous one. That's where things start to get messy, so we generally try to avoid doing that.

**Comment by raamdev** [comment]
@kristineds I tested this PR and the alignment looks great now! Thank you.

**Comment by kristineds** [comment]
> Once you push to GitHub, the only way to undo a commit is to push another commit that reverts the previous one. That's where things start to get messy, so we generally try to avoid doing that.

Noted. Thank you for the reminder! I was pulling my hair out earlier trying to understand Git and how to resolve that merge conflict. Ha! Appreciate all your help on this. :smile:

**Comment by raamdev** [comment]
> I was pulling my hair out earlier trying to understand Git and how to resolve that merge conflict.

Yep, that's one reason I keep recommending that everyone `git pull && git merge 000000-dev` into their feature branches _at least once a day_. The longer you wait, the more stuff in `000000-dev` might change, which will make it harder and harder to resolve a conflict if one occurs.

**Pull request closed without merging**
