### PR TITLE
Improve naming consistency of delivery options; 

### PR DESCRIPTION
**Pull request by renzms**
see: websharks/comment-mail#206

### CODE REVIEW

**Comment by raamdev** [comment]
Noting here that this is waiting a review from @kristineds. https://github.com/websharks/comment-mail/issues/206#issuecomment-175089892

**Comment by kristineds** [comment]
@raamdev @jaswsinc @renzms Tested this PR and it looks great! Attached are the screenshots that I took as part of my testing process. :) 

screen shot 2016-02-02 at 9 26 01 pm

screen shot 2016-02-02 at 9 25 36 pm

screen shot 2016-02-02 at 9 25 43 pm

screen shot 2016-02-02 at 9 25 49 pm

**Comment by jaswsinc** [comment]
@kristineds You might suggest a way that Renz could improve this just a bit. I don't think I included that in my outline, but we can probably get rid of the reference to `asap` here altogether.

**Comment by kristineds** [comment]
@jaswsinc Copy that. So it should look like this?

screen shot 2016-02-02 at 9 45 43 pm

Should it also be changed on other sections of the menu? Like for the RVE Handler notes:

screen shot 2016-02-02 at 9 46 15 pm

..and on the Subscr. Action Templates settings:

- https://github.com/websharks/comment-mail-pro/blob/78ccc101b44deba820bea28875f3f567b45baea6/comment-mail-pro/includes/classes/menu-page.php#L2989
- https://github.com/websharks/comment-mail-pro/blob/78ccc101b44deba820bea28875f3f567b45baea6/comment-mail-pro/includes/classes/menu-page.php#L3094

**Comment by jaswsinc** [comment]
> So it should look like this?

Yes. That looks great :-)

> Should it also be changed on other sections of the menu? Like for the RVE Handler notes:
> ..and on the Subscr. Action Templates settings:

Cool. Yes, those looks like nice enhancements also.

**Comment by renzms** [comment]
@raamdev @jaswsinc @kristineds Updated with enhancements.

**Comment by raamdev** [comment]
Changing this to `in progress` pending resolution to my inquiry here: https://github.com/websharks/comment-mail/issues/206#issuecomment-179316648

**Comment by raamdev** [comment]
@renzms Reviewed and merged. Thank you!

**Pull request closed without merging**
