### PR TITLE
Feature/Travis

### PR DESCRIPTION
**Pull request by jaswsinc**
@raamdev This PR adds Travis CI to Comment Mail and it also includes a starter test suite.

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc I get the following when I try to run `phing` on this branch:

```
[...]

PHP PSR-4 Project > -phpcs:

     [echo] Running PHP Code Sniffer.
    [mkdir] Created dir: /Users/raam/Projects/comment-mail-pro/.~build/.php-cs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   703  100   703    0     0    802      0 --:--:-- --:--:-- --:--:--   802
.........................Execution of target "-phpcs" failed for the following reason: /Users/raam/Projects/comment-mail-pro/phings/src/psr4/targets/phpcs.xml:11:10: /Users/raam/Projects/comment-mail-pro/phings/src/psr4/targets/phpcs.xml:32:52: Task exited with code 255

BUILD FAILED
/Users/raam/Projects/comment-mail-pro/phings/src/psr4/targets/phpcs.xml:11:10: /Users/raam/Projects/comment-mail-pro/phings/src/psr4/targets/phpcs.xml:32:52: Task exited with code 255
Total time: 9.8178 seconds
```

That error is not very informative... any idea what's going on? I confirmed that I'm using Phings v160406.

**Comment by jaswsinc** [comment]
Hmm. Can you see which version of PHPCS you're running for me?
They just released a new version the other day and I have found it to be buggy. I'm using v2.5.1.

**Comment by jaswsinc** [comment]
> any idea what's going on?

I interpret that error as meaning that the `phpcs` command line tool returned a non `0` exit status. Running `phpcs` for yourself from the command line may give you more information.

**Comment by raamdev** [comment]
> Can you see which version of PHPCS you're running for me?

```
$ phpcs --version
PHP_CodeSniffer version 2.5.1 (stable) by Squiz (http://www.squiz.net)
```

**Comment by raamdev** [comment]
Also, note that I can build Comet Cache just fine using the latest Travis CI integration that you added. It's just not working here for Comment Mail for some reason.

**Comment by jaswsinc** [comment]
@raamdev You might try altering some of the CLI args to see if you can narrow down a specific argument that results in the error exit status. See: https://github.com/websharks/phings/blob/000000-dev/src/psr4/targets/phpcs.xml#L38

Or, you might try running that command locally with all of those same arguments that our Phing script uses and then inspect the output to see if anything shows up at the command-line that Phing is missing; i.e., to shed light on the underlying issue.

**Comment by raamdev** [comment]
> Or, you might try running that command locally with all of those same arguments that our Phing script uses and then inspect the output to see if anything shows up at the command-line that Phing is missing; i.e., to shed light on the underlying issue.

Hmm, nope, nothing helpful shows up...

```
$ phpcs -p --report=full --encoding=utf-8 --extensions=php --ignore=*/vendor/* --standard=.~build/.php-cs/ws-psr2.xml .
......................... $ echo $?
255
```

I tried playing around with removing options, but nothing seems to change the `255` exit code. Any other ideas? I'm stumped. It works fine in the Comet Cache Pro project...

**Comment by jaswsinc** [comment]
Does changing `--ignore=*/vendor/*` to `--ignore='*/vendor/*'` make any difference?

**Comment by jaswsinc** [comment]
Also try using the full absolute path to the `--standard=` file.

**Comment by jaswsinc** [comment]
Those `.........................` indicate that it's working on several files and then choking on something specific. You might poke around the CLI options for that command-line and see if you can spit out more verbose output that would show you file names instead of just the dots.

**Comment by raamdev** [comment]
I think I might be running into a memory issue or something.

I ran the PHPCS command with `-vvv` to get extra verbose and it basically just "stops" on [line 3611 of `MenuPage.php`](https://github.com/websharks/comment-mail-pro/blob/feature/travis/src/includes/classes/MenuPage.php#L3611); no error, no extra information... and that line in `MenuPage.php` doesn't seem special in any way, except that it's line 3,611 in what is a rather large PHP file.

If I delete the file and run PHPCS again, it runs through the rest of the project just fine.

**Comment by raamdev** [comment]
I modified `/usr/local/bin/phpcs` to use PHP v5.6 instead of the PHP v5.4 (via MAMP) that it was using and now the entire process works fine (including `MenuPage.php`). I have XDebug enabled in MAMP for PHP v5.4, but it's disabled for PHP v5.6, so I'm thinking that might have had something to do with it too.

Anyway, all good now. :-)

**Comment by jaswsinc** [comment]
Ah, cool. Maybe it's the `php.ini` file for that version of PHP that is slightly different.

**Pull request closed without merging**
