### PR TITLE
Improve information displayed on Post small Meta box; See: websharks/comment-mail#231

### PR DESCRIPTION
**Pull request by kristineds**
Improve information displayed on Post small Meta box; 

See: websharks/comment-mail#231

### CODE REVIEW

**Comment by kristineds** [comment]
@raamdev @jaswsinc Submitting my PR for this ~ (still work in progress). Waiting on your feedback. :) 

So far I've got this:
- Changed text for `1` subscription ~ it now says "1 Subscription Total (View)"
screen shot 2016-02-26 at 12 44 53 am
- For subscriptions more than one:
screen shot 2016-02-26 at 12 44 34 am

Things I need help with:
- For zero or no subscriptions it says `Subscriptions Total (View All)`, it should be `Subscription Total (View)`
screen shot 2016-02-26 at 12 45 10 am
- Replacing the link text to `view` instead of the email address
- Adding the `last_update_time` per Post ID
- Change hover color for the Subscriptions button

**Comment by raamdev** [comment]
@kristineds Looks great so far! You said you needed help with something... are you stuck? Is there a specific question you have?

**Comment by kristineds** [comment]
@raamdev I'm stuck. :disappointed: Could you point me in the right direction on how and where I can change the following?

- How do I add the date/time per subscription?
postmetabox

- I was able to display the username of the subscriber but the text on the link to view the post is still displaying as an email address. How do I change it such that the text link is displayed as "View"?
post1
post3

- When a post has zero or no subscriptions, the button says `Subscriptions Total (View All)`. How can I change the button text to `Subscription Total (View)`? 
post4

**Comment by raamdev** [comment]
@kristineds writes...
> How do I add the date/time per subscription?

You'll need to update the [`lastXSubs()`](https://github.com/websharks/comment-mail-pro/blob/7be923a0a235d4fc73bf9a1e93b3284dd861069b/src/includes/classes/UtilsMarkup.php#L181-L249) method to also (optionally) output the insertion time (add a new `show_date` to the default args, with `true` as the default). 

Then you should be able to access the subscription date in the `foreach` loop of that method using `$_sub->insertion_time`, which is a Unix timestamp that you'll need to format for output using the `i18n()` method provided by Comment Mail (search the codebase for `utils_date->i18n()` for examples, and see the method definition in `src/includes/classes/UtilsDate.php`). 

For the "X hours ago" part, see the `utils_date->approxTimeDifference()` method (and search the codebase for examples of how to use it). 

---

> I was able to display the username of the subscriber but the text on the link to view the post is still displaying as an email address. How do I change it such that the text link is displayed as "View"?

You'll notice in the `lastXSubs()` method, the `nameEmail()` method is what generates the name, email address, and the link (i.e., anchor) that you want to change. The `nameEmail()` method already contains a way of overriding the default so that no link is attached to the email address--you just need to update the call in `lastXSubs()` to tell `nameEmail()` not to add that link.

Then, you'll need to add the `[view]` markup to the `lastXSubs()` method that links to the subscription (see the `nameEmail()` method for an example of how to get that URL--i.e., see how it's already being done when linking the email address to that page). 

----

> When a post has zero or no subscriptions, the button says Subscriptions Total (View All). How can I change the button text to Subscription Total (View)?

See `utils_markup->subsCount()` and `utils_i18n->subscriptions()` (which is called inside `subsCount()`). 

---

Keep in mind that if you ever change the way a method works, or change its default behavior in some way, you need to search the rest of the codebase for other areas that might be using that method. If the way a method works is changed, you need to make sure that other areas of the codebase are not expecting it to work the old way. If they are, then you'll need to decide if those areas of the codebase need to be updated as well (by passing a new default argument, for example).

That's why it's always best to try and avoid changing methods. That's also why methods should remain flexible enough that their behavior can be changed by simply passing in a new argument that overrides a default. This is the reason that many methods have a default set of arguments that can then be overridden when another method calls it.

**Comment by kristineds** [comment]
@raamdev Thank you for the instructions above. It really help a lot. Although, I still need to figure out how to fix the link for the "View" text. If you could look at the [`commit`](https://github.com/websharks/comment-mail-pro/pull/60/commits/afe061684e013db9478fe744698378f54b7d0329) I submitted and point me in the right direction, that will be very much appreciated. :) 

So far, this is what I came up with:

**Post Meta Box: With `X` Subscriptions**

Things I need help with: 

- [ ] How do I fix the link for the `[view]` markup? _I'm having a hard time figuring out how to get that URL._

screen shot 2016-03-22 at 2 51 39 am

**Post Meta Box: With No Subscriptions**

- [ ] How do I fix the if conditional statement such that the text "Subscriptions Total (View All)" won't get displayed when there's no subcriptions? 

screen shot 2016-03-22 at 1 55 35 am

**Comment by jaswsinc** [comment]
> I still need to figure out how to fix the link for the "View" text.

That is created by the call to `nameEmail('view', $view_args)`, which seems incorrect at the moment. The second argument to that function should be the email address, and `$view_args` should be the third argument. See also: https://github.com/websharks/comment-mail-pro/blob/feature/231/src/includes/classes/UtilsMarkup.php#L40

**Comment by jaswsinc** [comment]
> How do I fix the if conditional statement such that the text "Subscriptions Total (View All)" won't get displayed when there's no subcriptions?

That is controlled by this utility, which you can modify if you need to. See: https://github.com/websharks/comment-mail-pro/blob/feature/231/src/includes/classes/UtilsMarkup.php#L155

**Comment by kristineds** [comment]
@jaswsinc I was able to fix the if conditional statement, thanks for that. 
screen shot 2016-03-30 at 9 07 29 pm

However, for the `view` markup, after adding the 2nd argument for it, I came up with this. The link is added but how do I replace the email address with the text `view`? https://github.com/websharks/comment-mail-pro/pull/60/commits/be5b9b2657619da156c08a52bebcf1373011b52c

screen shot 2016-03-30 at 9 07 56 pm

**Comment by raamdev** [comment]
@kristineds At the end of [this line](https://github.com/websharks/comment-mail-pro/blob/feature/231/src/includes/classes/UtilsMarkup.php#L248) you're calling the `nameEmail()` method:

```php
$this->nameEmail('view',$_sub->email, $view_args)
```

That's passing three arguments (see [the `nameEmail()` method definition](https://github.com/websharks/comment-mail-pro/blob/feature/231/src/includes/classes/UtilsMarkup.php#L29-L40)): `$name`, `$email`, and `$args` (notice [where the `$args` are coming from](https://github.com/websharks/comment-mail-pro/blob/feature/231/src/includes/classes/UtilsMarkup.php#L216)).

Right now you're setting the `$name` to `'view'`. If you want the email address to appear there instead, then you would need to set it to `$_sub->email`.

However, that would give you the following:

> cupcake_test4@gmail.com <[cupcake_test4@gmail.com](mailto:cupcake_test4@gmail.com)>

What you actually want is this:

> [view](mailto:cupcake_test4@gmail.com)

---

A review of [the `nameEmail()` method](https://github.com/websharks/comment-mail-pro/blob/feature/231/src/includes/classes/UtilsMarkup.php#L29) will reveal that the method is specifically designed for outputting Name + Email, in the format of `"name" <email>`.

You don't want that. You want "[view](mailto:cupcake_test4@gmail.com)".

So, we really shouldn't be using `nameEmail()` at all here. I also wouldn't bother with a whole new method for this, since all we need to do is generate a link to the Comment Mail Subscriptions Search page, searching for the email address related to the subscription for that row.

---

So, we need two pieces of information to build the link: The text we want to use for the link (in this case, it's just `view`, so we've got that) and the link itself, which is a search link that searches the Comment Mail Subscriptions for a specific email address.

Let's do some reverse engineering to figure out how we can get the right search link. We already know that `nameEmail()` returns the right link, so let's start looking there.

---

Looking at the [the arguments `lastXSubs()` passes to `emailName()`](https://github.com/websharks/comment-mail-pro/blob/feature/231/src/includes/classes/UtilsMarkup.php#L216), we can see that it uses `'anchor_to' => 'search'`.

Now, taking a look at [what that argument does inside `nameEmail()`](https://github.com/websharks/comment-mail-pro/blob/feature/231/src/includes/classes/UtilsMarkup.php#L81-L83), we can learn what we need to do to get the Search URL

```php
$anchor_search_url = $this->plugin->utils_url->searchSubsShort('sub_email:'.$email);
```

So, to create the "[view](mailto:cupcake_test4@gmail.com)" link, all we need to do is replace the following on [this line in `lastXSubs()`](https://github.com/websharks/comment-mail-pro/blob/feature/231/src/includes/classes/UtilsMarkup.php#L249):

```php
.$this->nameEmail('view',$_sub->email, $view_args).
```

with this:

```php
.'<a href="'.$this->plugin->utils_url->searchSubsShort('sub_email:'.$_sub->email).'">view</a>'.
```

**Comment by jaswsinc** [comment]
Awesome. @kristineds Don't forget to use `esc_url()` there also.

```
.'<a href="'.esc_url($this->plugin->utils_url->searchSubsShort('sub_email:'.$_sub->email)).'">view</a>'.
```

**Comment by kristineds** [comment]
> Now, taking a look at [what that argument does inside `nameEmail()`](https://github.com/websharks/comment-mail-pro/blob/feature/231/src/includes/classes/UtilsMarkup.php#L81-L83), we can learn what we need to do to get the Search URL

@raamdev Aha! I racked my brain for hours but I still can't figure out that last part. Thank you for that very detailed explanation! I love how you explain what each method does and how to reverse engineer it.. :smile: 

> Don't forget to use `esc_url()` there also.

@jaswsinc Thanks for the reminder! I've added that too. 

I've submitted the PR but the [Travis Build says it failed](https://travis-ci.org/websharks/comment-mail-pro/builds/123084437)? 

- Submitting PR :https://github.com/websharks/comment-mail-pro/pull/60/commits/6400a2942a539f3f1b60ddc49068b0941980113c

screen shot 2016-04-14 at 11 12 09 pm

**Comment by raamdev** [comment]
> I've submitted the PR but the Travis Build says it failed?

Have you merged `000000-dev` anytime recently? (You should be doing this at least once a day.)

**Comment by kristineds** [comment]
> Have you merged 000000-dev anytime recently? (You should be doing this at least once a day.)

Yes. I did it 2hrs ago. https://github.com/websharks/comment-mail-pro/pull/60/commits/e8a1e2a9ae0f894c361800249743016275cfdf77

**Comment by raamdev** [comment]
> Yes. I did it 2hrs ago. e8a1e2a

Did you `git submodule update`? I checked out the `feature/231` branch and when I `cd` into the `phings` directory, I see that it says it's still using Phings v160219, which is very old (it should be v160411). 

After you run `git pull` and then `git merge 000000-dev`, a `git status` should tell you that the `phings` directory has "new commits". Running `git submodule update` should sync that submodule for you.

If you `cd phings` and then run `git status`, what do you see?

**Comment by kristineds** [comment]
>After you run `git pull` and then `git merge 000000-dev`, a `git status` should tell you that the `phings` directory has "new commits". Running `git submodule update` should sync that submodule for you.
>If you `cd phings` and then run `git status`, what do you see?

It says..

```
HEAD detached at 8817072
nothing to commit, working directory clean
```

**Comment by raamdev** [comment]
@kristineds If you run these commands, what do you see?

```
git checkout 000000-dev
git log -n 1
```

**Comment by kristineds** [comment]
@raamdev Hmm. I'm seeing this when I switch to `000000-dev` branch

```
Your branch is behind 'origin/000000-dev' by 63 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
```

and this after `git log -n 1`

```
commit 8817072255eac4342f665dedf9984d68c664f7ba
Author: jaswsinc <jaswsinc@wsharks.com>
Date:   Thu Feb 18 04:04:43 2016 -0900

    Updating changelog.
(END)
```

Looks like I forgot to update my `000000-dev` branch. :(  Should I resubmit the PR then?

**Comment by raamdev** [comment]
> Looks like I forgot to update my 000000-dev branch. :( Should I resubmit the PR then?

No, just run `git pull` from the `000000-dev` branch and then switch back to `feature/231` and run `git merge 000000-dev`. Then you'll need to run `git submodule update` also (from the `feature/231` branch).

**Comment by kristineds** [comment]
```
On `feature/231` branch
⇒  git submodule update
Submodule path 'phings': checked out '8817072255eac4342f665dedf9984d68c664f7ba'
```

after `git log -n 1`

```
commit 6400a2942a539f3f1b60ddc49068b0941980113c
Author: kristineds <kristine@websharks-inc.com>
Date:   Thu Apr 14 23:14:39 2016 +0800
```

**Comment by raamdev** [comment]
Just noting for the record that we continued the troubleshooting discussion on Slack. See https://websharks.slack.com/archives/comment-mail/p1460653768000012.

**Comment by kristineds** [comment]
@raamdev @jaswsinc:  _All checks have passed_. :grin: This is ready for review.

**Comment by raamdev** [comment]
@kristineds Woohoo! This looks great! I just tested it and it's working and looking as expected. :-) Nice work.

**Pull request closed without merging**
