### PR TITLE
Update DOCTYPE in email template; See: websharks/comment-mail#259

### PR DESCRIPTION
**Pull request by kristineds**
Update DOCTYPE in email template; 

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
```

See: websharks/comment-mail#259

### CODE REVIEW

**Comment by kristineds** [comment]
@raamdev I was able to update the DOCTYPE in the email templates. https://github.com/websharks/comment-mail-pro/pull/68/commits/7b7287a6f36651dda7f7265da73fd5771348a662

However, I tried testing it on my newly setup Outlook/Hotmail account but I'm not receiving the instant digest notifications. Not sure if it's just a glitch on my end. Would you mind testing this on your Hotmail account please? Thanks.

**Comment by raamdev** [comment]
Looks like it's working on my end:

**Comment by jaswsinc** [comment]
🙈 Shield thine eyes. Hotmail is back!? haha... This looks like fun. ugh.

**Comment by raamdev** [comment]
@jaswsinc As of mid-2015, Hotmail was second in place only to Gmail in terms of usage: http://blog.mailchimp.com/major-email-provider-trends-in-2015-gmail-takes-a-really-big-lead/

**Comment by jaswsinc** [comment]
Amazing. Guess we'd better get this fixed then. So the HTML5 doctype tag fails in Hotmail. Interesting.

The Hotmail fun continues years later. I find that sort of funny is all. I remember thinking of Hotmail in about the same way I thought of MSIE several years ago. Always a pain.

**Comment by Reedyseth** [comment]
> As of mid-2015, Hotmail was second in place only to Gmail in terms of usage:

To me that Outlook Mail is an attempt to be on the loop, but as a many years Gmail user I think that Outlook Mail still missing a lot and so there are those incompatibility bugs like MSIE as always. That is my opinion.

**Pull request closed without merging**
